spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xwh
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Jackson输出格式配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    locale: zh_CN