spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xwh
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialet: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true